### ISSUE TITLE
Create new table that lists the different types of conversations the user is having with chatbot

### ISSUE THREAD

**Issue by DavidChavarro** [Aletheianomous-AI/SQL_Datbase#1]
Create a new SQL table that represents a conversation each user is having with the chatbot.

The table should be named 'dbo.Conversation' and look like this

|  column name | description | column type |
| ------- | ----- | ----- |
| conversation_id | The identifier of the conversation | primary key, int | 
| conversation_title | The title or topic of the conversation, as generated by the chatbot | string | 
| user_id | The id of the user that is interacting with the chatbot in this conversation | int, foreign key with LOGIN table | 

Once done, the chat history table should have a new column that is a foreign key to the conversation_id column of the table "dbo.Conversation".

**Comment by EthanBByrd** [comment]
Table added and created.
